# Generated by Django 4.0.6 on 2022-07-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=200, verbose_name='zagolovok')),
                ('descriprion', models.TextField(max_length=1000, verbose_name='opisanie')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vremy sozdaniy')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='vremy izmeneniy')),
            ],
        ),
    ]
