# Generated by Django 4.0.6 on 2022-07-08 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracker',
            old_name='descriprion',
            new_name='description',
        ),
    ]
