# Generated by Django 4.0.6 on 2022-07-13 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_rename_descriprion_tracker_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'новый'), ('in progress', 'в процессе'), ('done', 'выполнено')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('task', 'задача'), ('bug', 'ошибка'), ('enhancement', 'улучшение')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='tracker',
            name='status',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='tracker_status', to='webapp.status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tracker',
            name='type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='tracker_type', to='webapp.type'),
            preserve_default=False,
        ),
    ]
