# Generated by Django 4.0.6 on 2022-07-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_status_status_alter_type_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracker',
            name='type',
        ),
        migrations.AddField(
            model_name='tracker',
            name='tracker_type',
            field=models.ManyToManyField(blank=True, related_name='trackers', to='webapp.type'),
        ),
    ]
