# Generated by Django 4.0.6 on 2022-07-21 11:41

from django.db import migrations, models
import webapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_remove_tracker_type_tracker_tracker_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='summary',
            field=models.CharField(max_length=200, validators=[webapp.validators.MinLengValidator(10)], verbose_name='zagolovok'),
        ),
    ]
